### ISSUE TITLE
Kids friendly option - use A1111 plugin to filter out nsfw content?

### ISSUE THREAD

**Issue by VictorZakharov** [Kilvoctu/aiyabot#103]
I installed the plugin in A1111 and it works, all nsfw content is blacked out.
Is it possible to make aiyabot use it also?

**Comment by Kilvoctu** [comment]
Heya, generally I don't support any extensions to Web UI (anything in [this list)](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Extensions#extensions-category) as they're out of scope. However, NSFW checker is sort of a basic thing, so I looked into it.  
> Is it possible to make Aiyabot use it also?  

As far as I can tell, it's not possible. There are no API endpoints and nothing in Web UI config for AIYA to connect to.  
It also doesn't appear in the Web UI script list, so I can't add something like `"script_name": "NSFW check"` to the payload.  
Automatic1111 moved the feature out of repo into an [extension](https://github.com/AUTOMATIC1111/stable-diffusion-webui-nsfw-censor). If you're able to convince them to add API support for it, I'll try to implement it.

In the meantime, I pushed a feature with commit 64dac4cc02cc06648a9360fea1e273f0b6c6ace9. When you launch AIYA, she'll add `prompt_ban_list = []` to the config.toml.
You can fill it out with any words you don't want to have processed, then restart bot. Afterward, she won't generate an image if any of the words are found in prompt.   

For example, I can enter the value like so in config.toml: `prompt_ban_list = ["unsavory thing"]`
And if I try to include it in prompt or 🖋️...
![image](https://user-images.githubusercontent.com/2993060/218341493-f17d4d03-5da1-482d-b0bc-b0256b60170c.png)
Any matches of the string will trigger, so if you ban `star` it'll catch `start` too.

It's not perfect, but it should be better than nothing.

**Comment by VictorZakharov** [comment]
@Kilvoctu I see. Prompt blacklist is good, but doesn't completely solve the problem. With most good models, asking for a female, full body will often result in nsfw content, even without explicitly asking for it. Similarly when asking for a female, outstanding beauty, pretty etc. And even when drawing female action shots, the content will not necessarily be nsfw, but very suggestive, so A1111's nsfw checker will block it also, which I think is the right thing to do.

Why can I not use discord's nsfw blocker? It blocks my posts, but not the bot?

**Comment by Kilvoctu** [comment]
Yeah, I'm aware it's not perfect. It's the best I can do with what I have available. Not sure what more I can do; I only manage this repo. 🤷‍♀️

> so A1111's nsfw checker will block it also, which I think is the right thing to do.

Yes, it's ideal, but you need to contact A1111 or leave feedback on that [extension repo](https://github.com/AUTOMATIC1111/stable-diffusion-webui-nsfw-censor). AIYA is not integrated into Web UI, like the stuff in the extensions list. She's a separate application that uses the API or can read through Web UI's config. 

> Why can I not use discord's nsfw blocker? It blocks my posts, but not the bot?  

This is a Discord feature, so you'll want to ask Discord Support. I simply don't know.

**Comment by VictorZakharov** [comment]
I created a ticket with A1111:
- https://github.com/AUTOMATIC1111/stable-diffusion-webui-nsfw-censor/issues/1

Not sure if it's the right place, because I was assigned ticket number 1, meaning no other tickets were created before this.

I also messaged discord support and asked them about this issue. I will keep this thread updated if I find anything. Thanks!
